baseURL = ""
languageCode = "en-us"
title = "Jake's Stuff"
relativeURLs = true
canonifyURLs = true

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[caches]
  [caches.images]
    dir = ":cacheDir/images"