baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[caches]
  [caches.images]
    dir = ':cacheDir/images'