baseURL = 'https://jakejmattson.github.io/stuff/'
languageCode = 'en-us'
title = "Jake's Stuff"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[caches]
  [caches.images]
    dir = ':cacheDir/images'